"""
models/test_case.py
===================
Dataclass representing a single generated test case.

A ``TestCase`` is produced by the testcase_generator module (Phase 3+).
It captures everything needed to execute one HTTP request and validate
the response — but contains no execution logic itself.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from constants.validation_types import TestStatus, Severity


@dataclass
class Assertion:
    """
    A single assertion rule attached to a test case.

    Attributes:
        assertion_id:  Unique identifier for this assertion.
        validation_type: Category of validation (status_code, json_path, …).
        operator:        Comparison operator (equals, contains, …).
        target:          The field, header name, or JSONPath expression to check.
        expected_value:  The value the target should match.
        description:     Human-readable description of what is being checked.
    """

    assertion_id: str
    validation_type: str   # Use ValidationType constants
    operator: str          # Use AssertionOperator constants
    target: str
    expected_value: Any

    description: Optional[str] = None

    def __repr__(self) -> str:
        return (
            f"Assertion(type={self.validation_type!r}, "
            f"op={self.operator!r}, target={self.target!r}, "
            f"expected={self.expected_value!r})"
        )


@dataclass
class TestCase:
    """
    A complete, executable test case for one API request/response cycle.

    Attributes:
        test_id:         Unique identifier generated by the test case generator.
        spec_id:         ID of the parent ``ApiSpec`` this case belongs to.
        endpoint_id:     ID of the ``Endpoint`` this case targets.
        name:            Human-readable test case name.
        description:     Detailed description of what the test verifies.
        method:          HTTP method (from the endpoint).
        path:            Resolved URL path (path parameters substituted).
        headers:         Request headers to send.
        query_params:    Query string parameters to send.
        path_params:     Path parameter substitutions applied to the URL.
        request_body:    Request body payload (for POST/PUT/PATCH).
        assertions:      List of ``Assertion`` rules to evaluate on the response.
        severity:        Importance level of this test case.
        tags:            Tags for grouping / filtering.
        status:          Current lifecycle status of the test case.
        created_at:      UTC timestamp of when the test case was generated.
        is_auto_generated: ``True`` if generated by the engine; ``False`` if manual.
        notes:           Free-text notes added by a user or generator.
    """

    test_id: str
    spec_id: str
    endpoint_id: str
    name: str

    method: str
    path: str

    description: Optional[str] = None
    headers: Dict[str, str] = field(default_factory=dict)
    query_params: Dict[str, Any] = field(default_factory=dict)
    path_params: Dict[str, Any] = field(default_factory=dict)
    request_body: Optional[Any] = None
    assertions: List[Assertion] = field(default_factory=list)
    severity: str = Severity.MEDIUM.value
    tags: List[str] = field(default_factory=list)
    status: str = TestStatus.PENDING.value
    created_at: Optional[datetime] = None
    is_auto_generated: bool = True
    notes: Optional[str] = None

    def __post_init__(self) -> None:
        if self.created_at is None:
            from datetime import timezone
            self.created_at = datetime.now(tz=timezone.utc)

    @property
    def assertion_count(self) -> int:
        """Return the number of assertions defined for this test case."""
        return len(self.assertions)

    @property
    def full_name(self) -> str:
        """Return a display-friendly label including method and path."""
        return f"[{self.method.upper()}] {self.path} — {self.name}"

    def __repr__(self) -> str:
        return (
            f"TestCase(id={self.test_id!r}, name={self.name!r}, "
            f"method={self.method!r}, path={self.path!r}, "
            f"assertions={self.assertion_count}, status={self.status!r})"
        )
